### PR TITLE
Added functionality to check for custom subarrays

### PR DESCRIPTION
**Pull request by tddesjardins**
These additions in utils_calib.py seem to catch all custom subarrays and also returns information about the number of bias columns.

### CODE REVIEW

**Comment by pllim** [comment]
Thank you for working on this, @tddesjardins ! I'll have a look soon. 😄

**Comment by pllim** [comment]
From looking at the hardcoded values, it seems like you only checked WFC subarrays. Are there no custom HRC subarrays? This OSCNTAB also affects HRC, so just want to double check.

**Comment by tddesjardins** [comment]
I'm not sure if there are custom HRC subarrays off the top of my head, but will look into this now.

**Comment by pllim** [comment]
Given that HRC is only 1k by 1k, it is probably unlikely users would be compelled to make their own subarrays, but with the coronograph, I can't be 100% sure. Thanks for checking!

**Comment by tddesjardins** [comment]
Yes, in fact the old instrument handbook says they find the likelihood a user would want to do a custom subarray with HRC to be remote, but says they can do it for nearly arbitrary image sizes (what a headache!).

**Comment by pllim** [comment]
@tddesjardins , hopefully my edits over at tddesjardins/acstools#1 would make this check easier.

**Pull request merged**
