### PR TITLE
[WIP] Updated Jenkinsfile for HSTCAL and new tests.

### PR DESCRIPTION
**Pull request by mdlpstsci**
Jenkinsfile needs to be updated to acquire and build the designated version of HSTCAL in support of the ACS tools which invoke the individual modules of the the HSTCAL calibration pipeline.

### CODE REVIEW

**Comment by pllim** [comment]
Note: When things are sorted out in `Jenkinsfile`, I also recommend running wrapper tests in `JenkinsfileRT`.

**Comment by pllim** [comment]
I am stumped by the difficulty in installing HSTCAL from source here -- https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Facstools/detail/PR-73/6/pipeline . @rendinam is not sure what is going on either. Is it possible that we move these wrapper tests over to HSTCAL repo instead? It is a lot easier to install `acstools` on top of HSTCAL rather than the other way around. @stscicrawford ?

**Comment by pllim** [comment]
p.s. Over at `stistools`, they test against *released* version of HSTCAL:
```
with_env -n stistools conda install -q -y -c http://ssb.stsci.edu/astroconda hstcal
```

**Comment by mdlpstsci** [comment]
Thanks for your investigation thus far.  You can stand down at this time as I need to resolve a higher priority issue.  Please know I appreciate your time and will look at this issue again (hopefully) soon.

**Comment by stscicrawford** [comment]
Short term, I don't have a problem with a test here against the released version and then wrapper tests in hstcal as it is more likely a pull request in hstcall that will break the tests and that's what we would catch.

**Comment by pllim** [comment]
FWIW using released version of HSTCAL, the tests ran but encountered error at missing Artifactory data, which is hopefully expected. There are also some PEP 8 stuff. When you have time again, @mdlpstsci , please let me know and we can revisit. Thanks!

**Comment by mdlpstsci** [comment]
Thanks.  I will take a look at the Jenkinsfile when this work pops to the top of the stack.  I am not surprised at the tests failing because the data is missing from Artifactory. I test all the regression tests with data on my system and make sure everything is happy **before** I populate Artifactory with the new data. I then run the regression tests again using the data on Artifactory.

**Comment by pllim** [comment]
@mdlpstsci , do you have plans to wrap this up or should we close this without merge? It has been opened for 1.5 years.

**Comment by mdlpstsci** [comment]
@pllim I will need to review as I have no memory of this.

**Comment by pllim** [comment]
I am just going to close this as stale. Please open new PR if you wish to revisit. Thanks!

**Pull request closed without merging**
