### PR TITLE
Update acstools to the latest bitmask in stsci.tools

### PR DESCRIPTION
**Pull request by mcara**
Update ``acstools`` to use latest ``bitmask`` functions - see https://github.com/spacetelescope/stsci.tools/pull/29

### CODE REVIEW

**Comment by pllim** [comment]
This seems non-backward compatible. `stsci.tools` is an *optional* dependency here, so its version compatibility is not checked on install. You need to add a version check right after that local import, or make this backward-compatible somehow.

**Comment by mcara** [comment]
@pllim take a look at the second attempt.

**Comment by mcara** [comment]
Ah, I just saw your approval. Thanks!

**Comment by pllim** [comment]
I don't see any need to do a immediate release of this change on AstroConda, so I'll wait and fold it into the next release whenever that may be. (Might have to do one before 2017.2 anyway but not guaranteed.)

**Comment by pllim** [comment]
Wait, wait... Write a test! :stuck_out_tongue_closed_eyes:

**Pull request merged**
