### PR TITLE
Update URL for query to a temporary instance of the old zeropoints ca…

### LINKED ISSUE #162: api supporting acszpt seems to have changed.
### Description
The acszpt module no longer works because of changes in the api at acszeropoints.stsci.edu

### Expected behavior
Return a table with zeropoint information.

### Actual behavior
Error, as the page being queried is no longer accessible,

### Steps to Reproduce
You can reproduce the error by running the python example code:

```python
from acstools import acszpt
date = '2016-04-01'
detector = 'WFC'
filt = 'F435W'
q = acszpt.Query(date=date, detector=detector, filt=filt)
zpt_table = q.fetch()
```
Which returns

```
INFO:acszpt.Query:Checking inputs...
INFO:acszpt.Query:Submitting request to https://acszeropoints.stsci.edu/results_single/?date1=2016-04-01&detector=WFC&WFC_filter=F435W
ERROR:acszpt.Query:<HTTPError 403: 'Forbidden'>
-------------------------------------------------------------------------------
The query failed! Please check your inputs. If the error persists, submit a ticket to the ACS Help Desk at hsthelp.stsci.edu with the error message displayed above.
```

### System Details

macOS-12.4-x86_64-i386-64bit
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)
[Clang 11.0.1 ]
Numpy 1.21.5
astropy 5.0.2
Scipy 1.8.0
Matplotlib 3.5.1
stsci.tools 4.0.1
ACS Tools 3.3.1

### PR DESCRIPTION
**Pull request by jryon**
…lculator

### Description

This pull request is to address errors caused by the old zeropoints calculator being taken down. It is available again at a new URL, which we update in this PR, to temporarily fix the querying problem. We will permanently fix this problem shortly.

Fixes #162

### CODE REVIEW

**Comment by pllim** [comment]
I have to close/re-open to kick off the previously inactive CI. Don't be alarmed.

**Comment by pllim** [comment]
> We will permanently fix this problem shortly.

What does this mean? Will the URL change again?

**Review by gsanand — APPROVED** [review]
update of acszeropoints.stsci.edu API link to acszeropointsapi.stsci.edu

**Comment by gsanand** [comment]
> > We will permanently fix this problem shortly.
> 
> What does this mean? Will the URL change again?

we will need to rewrite this file (acszpts.py) to work with the API for the new webpage (the one now hosted at acszeropoints.stsci.edu). this is a temporary fix so that users don't have to deal with a large downtime without a working API

**Comment by pllim** [comment]
CI failures are unrelated and the pipeline team is aware of the problem. Shall we merge? 

Do you need a release?

**Comment by jryon** [comment]
Yes to both. Thanks!

**Pull request merged**
