### PR TITLE
Pass arbitrary options to executables

### LINKED ISSUE #33: Add ability to pass arbitrary options through to called executable
This is effectively a backdoor to passing any and all options (whether they work or not) through to the underlying executable.

_c.f._ #31 

### Update:
Not applicable, at least under this issue, to ``destripe`` or ``destripe plus``. It covers the other wrappers in acstools:

* acs2d
* acsccd
* acscte
* acsrej
* acssum
* calacs

### PR DESCRIPTION
**Pull request by jamienoss**
Resolves #33

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
@tddesjardins hang tight.

**Comment by jamienoss** [comment]
@pllim thanks for the approval.

> Documentation wise, "arbitrary arguments" is not very informative to users; but that should be sufficient for now.

Do you have anything else in mind? I don't really see how it's _not_  informative. The logic is that "arbitrary" clearly implies that no checking is conducted to whether the passed arguments are valid. I.e. anything can be passed through.

**Comment by pllim** [comment]
As a user, I wouldn't know what to pass in as "arbitrary". It would be better to explicitly document all the acceptable options, but that can be battle for another day.

**Comment by jamienoss** [comment]
> As a user, I wouldn't know what to pass in as "arbitrary". It would be better to explicitly document all the acceptable options, but that can be battle for another day.

That would defeat the entire purpose and be poor design. That being said perhaps a link should be given to the actual documentation for the C executables. We really don't want to be duplicating anything.

**Comment by jamienoss** [comment]
>>As a user, I wouldn't know what to pass in as "arbitrary". It would be better to explicitly document all the acceptable options, but that can be battle for another day.
>
>That would defeat the entire purpose and be poor design. That being said perhaps a link should be given to the actual documentation for the C executables. We really don't want to be duplicating anything.

Actually... since this passes arbitrary arguments I'll just add to the docs ``--help'`` to get the full usage.

**Comment by pllim** [comment]
Yes, mentioning `--help` would be helpful. Thanks.

**Comment by jamienoss** [comment]
Going to merge and defer to #39

**Pull request merged**
