### PR TITLE
DOC: Improve layout

### LINKED ISSUE #121: DOC: API doc can be cleaned up
Use `automodapi` and so on, as brought up by @nmiles2718 .

### PR DESCRIPTION
**Pull request by pllim**
Fix #121

### CODE REVIEW

**Comment by pllim** [comment]
Failure is fixed upstream at readthedocs/readthedocs-sphinx-ext@e0a3828607d81f192f6310df4fbe16ee2437b3e7 . I guess we just have to wait for it to go into production on RTD side...

**Comment by jryon** [comment]
I checked out this branch locally and tried to build the html, but I'm getting an error:

```
(acstools_dev) ryon@jenna:/user/ryon/acstools/doc$ make html
sphinx-build -b html -d build/doctrees  -W source build/html
Running Sphinx v1.7.2

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/sw/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/sw/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 16, in <module>
    import stsci_rtd_theme
ModuleNotFoundError: No module named 'stsci_rtd_theme'
```

Is this related to the RTD failure that's fixed but not in production? I'm not super familiar with sphinx, so apologies if I'm way off base here.

**Comment by pllim** [comment]
@jryon , did you do the following?

```
pip install -e .[docs]
cd doc
make html
```

**Comment by jryon** [comment]
I had not run `pip install`, so thanks for the guidance there. Still getting an error associated with `stsci_rtd_theme`, however.

```
(acstools_dev) ryon@jenna:/user/ryon/acstools/doc$ make html
sphinx-build -b html -d build/doctrees  -W source build/html
Running Sphinx v3.0.2
loading pickled environment... failed
failed: build environment version not current

Theme error:
no theme named 'sphinx_rtd_theme' found, inherited by 'stsci_rtd_theme'
make: *** [Makefile:34: html] Error 2
```

**Comment by pllim** [comment]
I guess you have to install https://pypi.org/project/sphinx-rtd-theme/ too. Weird, I thought `stsci_rtd_theme` would install it for you. 🤷

**Comment by jryon** [comment]
According to `conda list`, I already have `stsci-rtd-theme`:

`stsci-rtd-theme           0.0.2                    pypi_0    pypi`

**Comment by pllim** [comment]
`sphinx-rtd-theme` and `stsci-rtd-theme` are two separate packages.

**Comment by jryon** [comment]
Oops, my eyes apparently weren't attached to my brain just then. Thanks for your help, the docs are now built.

My only requested change involves the navigation panel on the left. I see that under `Calibration Utilities` and `Satellite Detection`, there's an expandable menu of pages for the functions available within those subpackages. If it's possible to add such a function menu to the modules under `CALACS > Pipeline Python Wrappers` and `CALACS > CTE Forward Model`, I think that'd be helpful. Similarly for the modules under `Standalone WFC Destriping Tools`, there's a subheading for `Functions`, but no expandable menu for the function pages themselves. I see that the functions are listed on the actual page for each package, but it isn't obvious that they link to another page describing the available input parameters. Let me know if this isn't clear and I'll attach screenshots or something.

**Comment by pllim** [comment]
The menu and ToC stuff are determined by the theme and `automodapi` stuff, so I am not sure how easy it is to customize it, but I can investigate. Thanks for the review!

**Comment by pllim** [comment]
There might be a bug in the STScI theme preventing the left menu to work as expected, so I reverted the theme. Had to change the wrapper section a little. What do you think of https://acstools--122.org.readthedocs.build/en/122/ ?

**Comment by jryon** [comment]
Looks great. Thanks for implementing the changes to the menu!

**Comment by pllim** [comment]
Thanks for your thorough review, @jryon !

**Pull request merged**
